[versions]
# Build Tools
agp = "8.8.0"

# Kotlin
kotlin = "2.0.0"
ksp = "2.0.0-1.0.24"

# AndroidX
androidxCore = "1.15.0"
androidxAppCompat = "1.7.0"
androidxActivity = "1.10.1"
androidxLifecycle = "2.8.7"
androidxNavigation = "2.8.8"

# Compose
androidxCompose = "2025.01.00"
androidxComposeMaterial3 = "1.3.1"
androidxComposeGraphics = "1.6.0"

# Google
app-update = "2.1.0"
google-services = "4.4.2"
billing-client = "7.1.1"

# Hilt
hilt = "2.51.1"
hiltNavigation = "1.2.0"

# Network
okhttp = "4.12.0"
retrofit = "2.11.0"

# Kotlin Extensions
kotlinxSerialization = "1.7.3"
kotlinxImmutable = "0.3.8"
kotlinxCoroutines = "1.9.0"

# Java Extensions
javax = "1"

# UI Libraries
coil-compose = "3.0.4"
lottie = "6.0.1"

# Amplitude
amplitude = "1.17.3"

# Firebase
firebase-bom = "33.10.0"
firebase-crashlytics = "3.0.3"

# Kakao
kakao = "2.20.6"

# Test
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.0"

# Etc
timber = "5.0.1"
phoenix = "3.0.0"

[libraries]
# Gradle Plugin
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "androidxComposeMaterial3" }
androidx-ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "androidxComposeGraphics" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigation" }

# Network
retrofit-bom = { group = "com.squareup.retrofit2", name = "retrofit-bom", version.ref = "retrofit" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit" }
retrofit-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization" }
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }

# Kotlin Extensions
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

# Java Extensions
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javax" }

# Third Libraries
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
phoenix = { group = "com.jakewharton", name = "process-phoenix", version.ref = "phoenix" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# UI Libraries
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil-compose" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil-compose" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

# Analytics
amplitude = { group = "com.amplitude", name = "analytics-android", version.ref = "amplitude" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx" }

# Kakao
kakao = { group = "com.kakao.sdk", name = "v2-user", version.ref = "kakao" }

# Google
app-update = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "app-update" }
billing-client = { group = "com.android.billingclient", name = "billing-ktx", version.ref = "billing-client" }

[bundles]
androidx = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "androidx-lifecycle-runtime",
    "androidx-lifecycle-viewModel",
    "androidx-activity",
]

compose = [
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling-preview",
    "androidx-compose-animation",
    "androidx-compose-foundation",
    "androidx-compose-runtime",
    "androidx-compose-material3",
    "androidx-compose-material3-android",
    "androidx-ui-graphics-android",
]

navigation = [
    "androidx-navigation",
    "hilt-navigation",
]

retrofit = [
    "retrofit",
    "retrofit-serialization",
]

okhttp = [
    "okhttp",
    "okhttp-logging-interceptor",
]

coroutines = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-android",
]

kotlinx = [
    "kotlinx-serialization",
    "kotlinx-immutable",
]

androidx-test = [
    "androidx-junit",
    "androidx-espresso-core",
]

androidx-ui-test = [
    "androidx-ui-test-manifest",
    "androidx-ui-test-junit4",
    "androidx-ui-tooling",
]

ui = [
    "coil-compose",
    "coil-network-okhttp",
    "lottie-compose"
]

firebase = [
    "firebase-crashlytics",
    "firebase-analytics",
    "firebase-messaging"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
java-library = { id = "java-library" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
